### ISSUE TITLE
Compile Directive Misplaces Static Content

### ISSUE THREAD

**Issue by jgrasser** [GoogleCloudPlatform/appengine-try-java#1]
I downloaded this application and ran 'ant runserver'. Dev_appserver died because it could not find the appengine.xml file. 

After examination of the build file, I saw that the compile directive was misplacing the static content. The diff below fixes the issue. 

<     <copy todir="war/WEB-INF/classes">
## <       <fileset dir="src">

> ```
> <copy todir="war/">
>   <fileset dir="src/main/webapp/">
> ```

**Comment by tswast** [comment]
The App Engine team no longer supports Ant. These are currently supported App Engine plugins:

- [App Engine Maven plugin](https://cloud.google.com/appengine/docs/java/tools/using-maven)
- [App Engine Gradle plugin](https://cloud.google.com/appengine/docs/java/tools/gradle)
- [App Engine Eclipse plugin](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/wiki/Google-Cloud-Tools-for-Eclipse)
- [App Engine IntelliJ plugin](https://cloud.google.com/tools/intellij/docs/deploy-std)
