### ISSUE TITLE
After installation

### ISSUE THREAD

**Issue by csselo** [GoogleCloudPlatform/appengine-try-java#2]
Hi

I installed it succesfully.

[INFO] Installing /home/selo/İndirilenler/appengine-try-java-master/target/appengine-try-java-1.0.war to /home/selo/.m2/repository/com/google/appengine/demos/appengine-try-java/1.0/appengine-try-java-1.0.war
[INFO] Installing /home/selo/İndirilenler/appengine-try-java-master/pom.xml to /home/selo/.m2/repository/com/google/appengine/demos/appengine-try-java/1.0/appengine-try-java-1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

but there is no info about after installation.
how can I see this app

**Comment by waprin** [comment]
Use

`mvn appengine:devserver` to run locally and 

`mvn appengine:upload` to deploy. 

See App Engine Java tutorial: 

https://cloud.google.com/appengine/docs/java/gettingstarted/introduction

**Comment by tswast** [comment]
Hi @csselo hopefully you solved your problem. I've recently updated the plugin to use the [new App Engine Maven plugin, based on the Cloud SDK](https://cloud.google.com/appengine/docs/java/tools/using-maven).

The new commands are `mvn appengine:run` to run locally and `mvn appengine:deploy` to deploy.

I've also added a README with this information.
