### ISSUE TITLE
Java 8 version

### ISSUE THREAD

**Issue by husayt** [GoogleCloudPlatform/appengine-try-java#44]
As java 7 is deprecated on Appengine, would be nice to have this running with java 8.

**Comment by tswast** [comment]
Fixed by https://github.com/GoogleCloudPlatform/appengine-try-java/pull/42, no?

**Comment by husayt** [comment]
I don't think so. It still says jdk 1.7 in pom.xml. So you are effectively
deploying java 1.7 bundle to run in java 8 appengine environment.
