### ISSUE TITLE
Needs tests and README

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/appengine-try-java#6]
We need to test both master & gcloud branches.
- [x] README
- [x] Travis for checking that it builds https://github.com/GoogleCloudPlatform/appengine-try-java/pull/8 https://github.com/GoogleCloudPlatform/appengine-try-java/pull/7
- [x] Travis for linting with checkstyle https://github.com/GoogleCloudPlatform/appengine-try-java/pull/8 https://github.com/GoogleCloudPlatform/appengine-try-java/pull/7
- [x] Travis unit and integration tests
- [x] Jenkins deployment tests
- [ ] Remove build.xml

**Comment by ludoch** [comment]
also remove build.xml, Ant support is not there.
